### ISSUE TITLE
The request url is outside of Vite serving allow list. (x3)

### ISSUE THREAD

**Issue by aminnairi** [slidevjs/slidev#1238]
**Describe the bug**
When using slidev as a global user binary (installed at `$HOME/.local/lib/node_modules/.bin/slidev` using `npm install --prefix $HOME/.local/lib/node_modules`), the `slidev` binary reports the following error:

```
The request url "/home/amin/.local/lib/node_modules/@slidev/client/main.ts" is outside of Vite serving allow list. (x3)
```

**To Reproduce**
1. Install `@slidev/cli`, `@slidev/theme-default` & `playwright-chromium` for the current unprivileged user at `$HOME/.local/lib/node_modules/`
2. Add the `$HOME/.local/lib/node_modules/.bin` in your `PATH` environment variable's directory list
3. Restart the shell
4. Try running `slidev`
5. See the error

**Desktop (please complete the following information):**
 - OS:Archlinux
 - Browser: N/A
 - Slidev version: 0.46.1

**Rationale**

It would be great to be able to use Slidev as a global binary for quickly serving markdown slides instead of having to initialize a new project using `npm init slidev` or use `npx @slidev/cli` since it requires more than just `@slidev/cli` (for exporting slides for instance).

This would also allow one to be able to quickly add Slidev in their dotfiles in order to quickly reinstall an operating system and be ready presenting multiples folders without having to manually type `npm install` for each presentation folders.

**Comment by KermanX** [comment]
It seems that this has been fixed by 2a152cf3c5915bf7f0409f6d71b4d3367964966a.

**Comment by aminnairi** [comment]
I'm still getting the same error using the latest version
![image](https://github.com/slidevjs/slidev/assets/18418459/ba796942-6941-4591-9cbc-12d3344f020e)
Not really sure how I can help anymore?
