### ISSUE TITLE
Mermaid flows not loading anymore after v0.50.0

### ISSUE THREAD

**Issue by estruyf** [slidevjs/slidev#2067]
**Describe the bug**

I just installed the latest version and created a slide with a Mermaid flowchart, but the flowchart itself doesn't show up on the slide.

When I used version 0.50.0, it showed the following:

![Image](https://github.com/user-attachments/assets/91b2344a-10f9-4d07-8623-fbaa20503896)

![Image](https://github.com/user-attachments/assets/12fcd829-31c4-441f-a464-0df9b5341c02)

Any version newer than 0.50.0, it shows the following:

![Image](https://github.com/user-attachments/assets/833b3437-f5b3-4811-9e97-ed2bd42dc787)

![Image](https://github.com/user-attachments/assets/3d4fbf5f-233b-4d1d-bcd0-b72f7a9b20be)

**Minimal reproduction**

1. Create a new project
2. Add a slide with Mermaid:
  ```mermaid
  flowchart LR
    a["Playwright authentication"]
    b["Using Time-based One-Time Password (TOPT)"]
    c["Using an authenticated state"]
  
    a --> b
    a --> c
  ```
3. View the slide in the browser

Stackblitz: https://stackblitz.com/edit/github-eozuw6vs?file=slides.md

**Environment**

- Slidev version: > 0.50.0
- Browser: Chrome
- OS: macOS

**Comment by kermanx** [comment]
I think this is of the same cause as #2066.

**Comment by antfu** [comment]
Should be fixed in 5.1.2

**Comment by estruyf** [comment]
> Should be fixed in 5.1.2

Thanks @antfu 🙏

**Comment by estruyf** [comment]
Still the same in 51.1.2

![Image](https://github.com/user-attachments/assets/b9e1c47e-5b79-4485-a95e-60b818b482b1)

https://stackblitz.com/edit/github-eozuw6vs?file=package.json

**Comment by kermanx** [comment]
> Still the same in 51.1.2
> 
> ![Image](https://github.com/user-attachments/assets/b9e1c47e-5b79-4485-a95e-60b818b482b1)
> 
> https://stackblitz.com/edit/github-eozuw6vs?file=package.json

How about the latest version?

**Comment by estruyf** [comment]
@kermanx same

**Comment by bravohenry** [comment]
Same issue here
