### ISSUE TITLE
Cannot read properties of undefined (reading 'nav')

### ISSUE THREAD

**Issue by Jason7158** [slidevjs/slidev#672]
在slidev中使用$slidev.nav.clicks，比如
```vue
<div v-if="$slidev.nav.clicks <= 3" >
  111
</div>
```
浏览器报错
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nav')

"dependencies": {
    "@slidev/cli": "^0.35.2",
    "@slidev/theme-apple-basic": "^0.20.0",
    "@slidev/theme-default": "*",
    "@slidev/theme-seriph": "*"
 }

 - OS: Win10专业版 21H2
 - Browser: Microsoft Edge 103.0.1264.77 (正式版本) (64 位)
 - Slidev version:

**Comment by alexanderdavide** [comment]
This issue must have been introduced with the latest minor release of v0.35.*.

For the time being, you can pin Slidev to < v0.35. I've tried v0.34.3 successfully.

**Comment by antfu** [comment]
Should be fixed in 0.35.4

**Comment by alexanderdavide** [comment]
For me, the error still occurs with v0.35.4. @Jason7158, is it working for you? 

Simple repro that works with a version < 0.35:

```markdown
---
theme: seriph
---

Cannot read properties of undefined (reading 'nav')

<SlideCurrentNo /> / <SlidesTotal />
```

**Comment by Jason7158** [comment]
I ended up using V0.35.4.

**Comment by htharoldht** [comment]
@alexanderdavide I have this problem too, did you finally solve it?

**Comment by ChiMaoShuPhy** [comment]
same issue with latest v0.35.4, it was working properly with previous release of v0.35.4

**Comment by alexanderdavide** [comment]
Sadly, I have not, @htharoldht. I am wondering how @Jason7158 now runs on v0.35.4.

@antfu, this issue should probably be reopened.

**Comment by janvorisek** [comment]
The issue is still present in `0.41.1`.

{{ $slidev }} is empty
